[package]
name = "clipboard-ext"
version = "0.1.0"
authors = ["Tim Visée <3a4fb3964f@sinenomine.email>"]
description = "A clipboard library providing useful extensions for rust-clipboard."
repository = "https://gitlab.com/timvisee/rust-clipboard-ext"
license = "MIT / Apache-2.0"
keywords = ["clipboard"]
edition = "2018"

[dependencies]
clipboard = "0.5.0"

[target.'cfg(all(unix, not(any(target_os="macos", target_os="android", target_os="emscripten"))))'.dependencies]
libc = "0.2"
which = "3.1"
x11-clipboard = "0.3.0"
